<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="ExtentReportProject" duration-ms="44470" started-at="2020-07-10T23:05:54 EDT" finished-at="2020-07-10T23:06:38 EDT">
    <groups>
    </groups>
    <test name="TestCase 1" duration-ms="16723" started-at="2020-07-10T23:05:54 EDT" finished-at="2020-07-10T23:06:10 EDT">
      <class name="TestCase.TestClass1">
        <test-method status="PASS" signature="clickAcademyTest()[pri:0, instance:TestCase.TestClass1@4206a205]" name="clickAcademyTest" duration-ms="16661" started-at="2020-07-10T23:05:54 EDT" finished-at="2020-07-10T23:06:10 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clickAcademyTest -->
      </class> <!-- TestCase.TestClass1 -->
    </test> <!-- TestCase 1 -->
    <test name="TestCase 2" duration-ms="15605" started-at="2020-07-10T23:06:11 EDT" finished-at="2020-07-10T23:06:26 EDT">
      <class name="TestCase.TestClass2">
        <test-method status="PASS" signature="googleTest()[pri:0, instance:TestCase.TestClass2@29f69090]" name="googleTest" duration-ms="15583" started-at="2020-07-10T23:06:11 EDT" finished-at="2020-07-10T23:06:26 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- googleTest -->
      </class> <!-- TestCase.TestClass2 -->
    </test> <!-- TestCase 2 -->
    <test name="TestCase 3" duration-ms="11686" started-at="2020-07-10T23:06:26 EDT" finished-at="2020-07-10T23:06:38 EDT">
      <class name="TestCase.TestClass3">
        <test-method status="FAIL" signature="facebookTest()[pri:0, instance:TestCase.TestClass3@35083305]" name="facebookTest" duration-ms="11226" started-at="2020-07-10T23:06:26 EDT" finished-at="2020-07-10T23:06:38 EDT">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at org.testng.Assert.assertTrue(Assert.java:53)
at TestCase.TestClass3.facebookTest(TestClass3.java:26)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- facebookTest -->
      </class> <!-- TestCase.TestClass3 -->
    </test> <!-- TestCase 3 -->
  </suite> <!-- ExtentReportProject -->
</testng-results>
